services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    depends_on:
      - redis
    command: flask run --host=0.0.0.0

  celery_worker:
    build: .
    volumes:
      - .:/app
    depends_on:
      - redis
    command: celery -A celery_tasks.tasks worker --loglevel=info

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
